version: "1"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./docker/production/django/Dockerfile
    image: archfndr_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./docker/production/postgres/Dockerfile
    image: archfndr_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./docker/production/traefik/Dockerfile
    image: archfndr_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: archfndr_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: archfndr_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: archfndr_production_flower
    ports:
      - "5555:5555"
    command: /start-flower
  awscli:
    build:
      context: .
      dockerfile: ./docker/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups
